---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "translation-service"
  namespace: "default"
  labels:
    app: "translation-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "translation-service"
  template:
    metadata:
      labels:
        app: "translation-service"
    spec:
      containers:
      - name: "translation-service"
        image: "gcr.io/conference-console/translation-service"
        imagePullSecrets:
          - name: gcrsecret
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "translation-service-hpa"
  namespace: "default"
  labels:
    app: "translation-service"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "translation-service"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: translation-service
  labels:
    app: translation-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: http
  selector:
    app: translation-service
